version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: makeup-sdk-frontend
    restart: unless-stopped
    ports:
      - "3030:3030"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - frontend-network

networks:
  frontend-network:
    driver: bridge